apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp01-test 
  namespace: sanservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sftp01-test
  template:
    metadata:
      namespace: sanservices
      labels:
        app: sftp01-test
    spec:
      containers:
        - name: sftp01-test
          image: linuxserver/openssh-server:latest
          env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "America/Argentina/Buenos_Aires"
          - name: PUBLIC_KEY
            value: "-----BEGIN RSA PRIVATE KEY-----
          MIIJKAIBAAKCAgEA7gzrbMbtw+m3viImCz3USqu/TpCan6Ely9Pb0nIphmuNeH0l
          GVpzTs72TwODT0gdnMcsd3QOuuxw7xpsNdif4XhFljM488NknODJJKOa3+94kwKg
          bPs0LfgiEYubHKmw9w6oFGijCOdSmOiu8tCh2342OSD5r8CXNT95V3t3MZzC7mni
          qkJS0nyzPMe87qqV5w2FJRfXyHR2G7tCjYTcT3PBut9NdeD/cD8W1tGvg+nWbKbN
          IcG57i8NLin4m8++AK6NXN8bBpsr4wkmhXoAgnuKIsQcJPvhf82P0d6L3HGXSLvw
          kstor1fp4qCBN6Hwg6iGVoaE48OB1wQ9XrXPkWwpwVJ2K3Y8IQW3dtXiVgjCHCgc
          yOFx43otuMlJ1ffGMgpPmVwTfesI/PSqkjDDzgbA/+bhkfyugGhL2973jyTOEOOJ
          Fh3zlPrZRObXGzZOYOFBjGBdmjGO26xftOhfvraOju4rSeH1/7JwACwk/Fbs8B0A
          is0OefVM340J1Ylgbt+00ZRExu+reC0Rru7/dB9K5PLTGWPiu/6ATijzHf82soXO
          3TVA4Wgdiw2/ZU4h//EkTnmfjOHxmwTJlwiqp8x0IHPceHCAerMRoHHRU/peSlOt
          lfzV/9QhgitgEBYSoYcnXsS2URHM46ybLISypBad+Q4Olb0MLwVAYwUqI8MCAwEA
          AQKCAgBgMcJUw5JDD8fbQktjUYne3sZAxjhldyYh1qvGv7E+C2ownUmHlEByQTnR
          Nhcyy26D8wxp/PES4gbE6EWAANiisQpVpr9F6dhXeJJvhtlH0qpDpdUUFPLB/Lov
          ot18WKoVO8v560quh2OePLCtmFc/riHVNhkPx2CS+OJc0pyY5ML0ur8IlCKJwjBf
          yEr1muNWaeU61wawjzdG/4XmUCECzkEj9aaEkvZF8oiVKEinoq+uWj0cff9XW5YU
          6Ir405rxBZhERjfSlJPIe+MgHuvjzm5EnEDPRSWbkoKiiS61VwWOM7wEZcQYzwrJ
          NJji1UKuwUP/5P4AV/m43JK8GfYVAzgwdN+NxU5TQIDQH5Uzy66xI2WVDgT22hrD
          34BIF7FHPt82iw1ysPWj5IE5hCeJ9auzeM6qK3RL8gEcbnATtlLecYMW+iCToK6c
          TKSnL32LM7hG5DjiLldJ6xrGrQZN/7s2xEB7u3Qa+XskgaGTv5RYjWzmi2JqVJ/u
          1DZVwkwMz5UgOGu7ZOUkY3ivzyoNfG0yeuUBq/2Ok9QPlX8ibQr8ffJEhN6j/2yw
          GbRamomkGaQnADvWma+61Gtruo1OraEwVUgkE2Oku2OwAG7e0+ERqy84nAF+VGv8
          XfoKLPih5cw7ePORxBBNyuXgAciIo//eqwQbf3fQ1d9eztf/qQKCAQEA+zZ3f0Ai
          Si5+iax+q71hemlgumH4anLF05lArroXoTTjkobTAPpif/MH+MBzpSo/rcmR0hqP
          Zj3JFhc1kBHl/2hrQMN2qDfwWnZyagnMhjxIOzBVZcZtb3jsfgN5AV4SprPCJkM/
          EvBL/YSs+pvxB/OWZ8oE9qqKDNmCPjH83BlMLSQbfjsDzU/JQ5dcGkYite3/TU5G
          XbnF2kIOIQyoJFJqoSRDn6CI8N8IZil1B4yXQwQk7QUaolLLIMTBTI1fT9Y4rULh
          O3Uu6SZLh16itJapu7CzrzZ0zL8ML16W5FeeBuH9BGB5FM0OyQJaO/9YNmTJHV3S
          9Oq12V4OU5jjtwKCAQEA8pY9s9pDyCrmU4UZvhQaUJd/vJUtjs4d/38xd62bhPau
          NsMu+/0bAiRmd+CqSpdwHjxU/dFkaYtQjYTtJjSgJIMELlK9lC/gWpJaW8WQ6/oi
          xF4J7/0MCNwdsV/XfOWNQ4yreZrOcQaqHJ8EYlJdyEAAjiLj6Ovt6BmgEGBKWYdK
          pLQ6apArCzsB6bp6WXAMeX1jKBIp3l7CmvY/3HOhv8/IUvRo0LT5rzKHRX6ZuON4
          U+BCkAbeRHhENQquhwZyzsPCkwE97mTRKvox81yhfU49Ib9PVJKOwFULs2Lwp1r1
          SXrHBECW8gbwG7IA95orOgfXtGvpGDIsmv/bDB24VQKCAQA2JpyFqp55nSIbrTo0
          7QLJL1PxeVLiJ1FrdlqSD30ue8cee7+aM17uM8YhIeML1FqbrJqpTp5grKre/yvF
          nYYVkz2jXT8DreM6rNOm9evHd9EeKSIPaUGHyOo5k6gO2mds1czhEJfVDkVjJalf
          8CN50lE2mD6PqV1OvcgsffwCudVI2cKvaCs+o5c/4a2x4DJ1QxNIZ7oVVAlJLfn7
          t8263qUrjTSigSljusAFvaQDd5PXl1oaWYJPQUeWDbOZO9Qy0nuvJX6FoZH2IhIf
          4Q9znBKEaeehujxdMkV/JIWkPRrMYwR2YBFZoYYxYDdxPW6XcwxDL0ldEAcZDwRJ
          kuhrAoIBAChmAMyM0rDpBAZwqgLPkjpNoIYlSbr4dGJyKijGDposAoM4KgDo+7B1
          o2LfVTyqz48ZeQXz8wbonneS5XNxXCH4d5/HQ68D8hbjPIz/78x8kYGmL3155KEt
          FvzM+zPffpD7Qis0LqD//SBbEv3Uva11iyIgiVfmwm3epptTjc4vC602HmxUqfZq
          0zy7Q1jVoh4xVWv86mAP49SuoZ/y2cL5tWCrNzFakiItBf36wVra9tTxCeS2YBmC
          9cjniH0QA9qPGz4j/M5Ql8zScbMXgAVAHEocc/efmIpLH3G2TmFwclzUR4RbxUd1
          BFN4Z1TUpdI6MB/pwJ247Vi6tx3jbSkCggEBALMsalA8qOITKTspjpgSggt8o2lK
          3EcDEo5XAsGUzOVvGMn00DlakU+iBMc2ocqPbwekk3nx5lZlY2fFWH6LY5a4uxP3
          W5UnlbPaiFwjfUQYZlIR+/5e/VoHJjcsWZSFgMfx7u9DXZOdv8YXRfO9SobT4EGV
          d+veCNT4M2D16/AfVLVJvJsAnnz7/JnOj8JQvBHMmUgLA53sbsieXjfSDBdyy9RQ
          YQXJtcKqDmp+4sb/v9wZ6Up3QObM9AjiD65TApT4HoVPo4Aq/a3MEUWPIRX1cMHg
          1yQ0f8bnrLXD93CijsisuyWwFyF/p9IsHUHqr7aIfTHp2CRUJCYfXRSK3N4=
          -----END RSA PRIVATE KEY-----"
          - name: SUDO_ACCESS
            value: "false"
          - name: PASSWORD_ACCESS
            value: "true"
          - name: USER_PASSWORD
            value: "test"
          - name: USER_NAME
            value: "asalad"
          volumeMounts:
          - name: ftpservices
            mountPath: "/home/asalad/upload"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 22
      volumes:
      - name: ftpservices
        persistentVolumeClaim:
          claimName: sftp01
---
apiVersion: v1
kind: Service
metadata:
  name: sftp01-test
  namespace: sanservices
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "ear-prod-container1-subnet"
spec:
  type: LoadBalancer
  # loadBalancerIP: 172.21.45.142
  ports:
     - protocol: SFTP 
       port: 8122
       targetPort: 22
      