apiVersion: apps/v1
kind: Deployment
metadata:
  name: stg-apiservices-dev  
  #namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stg-apiservices-dev
  template:
    metadata:
      #namespace: dev
      labels:
        app: stg-apiservices-dev
    spec:
      containers:
        - name: stg-apiservices-dev
          image: eardevacr01.azurecr.io/stgapiservices:v1.dev
          #namespace: dev
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: stg-apiservices-dev
  #namespace: dev
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 172.21.45.142
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: stg-apiservices-dev