apiVersion: apps/v1
kind: Deployment
metadata:
  name: stg-apiservices-preprod  
  namespace: preprod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stg-apiservices-preprod
  template:
    metadata:
      namespace: preprod
      labels:
        app: stg-apiservices-preprod
    spec:
      containers:
      - name: stg-apiservices-preprod
        image: eardevacr01.azurecr.io/stgapiservices:v1.preprod
        namespace: preprod
      ports:
        - containerPort: 80
          env:
        - name: TITLE
          value: "Storage Api Service"
---
apiVersion: v1
kind: Service
metadata:
  name: stg-apiservices-preprod
  namespace: preprod
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 172.21.45.142
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: stg-apiservices-preprod