apiVersion: apps/v1
kind: Deployment
metadata:
  name: fumon-web-dev  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fumon-web-dev
  template:
    metadata:
      labels:
        app: fumon-web-dev
    spec:
      containers:
      - name: fumon-web-dev
        image: eardevacr01.azurecr.io/fumon:dev
      ports:
        - containerPort: 8100
          env:
        - name: TITLE
          value: "Fumon Web in DEV"
---
apiVersion: v1
kind: Service
metadata:
  name: fumon-web-dev 
spec:
  type: ClusterIP
  ports:
  - port: 8100
  selector:
    app: fumon-web-dev